# .rubocop.yml
require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/*"
    - "config/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Rails/StrongParametersExpect:
  Enabled: false

